In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("C:/Users/sai/Documents/great lakes/New batch/New folder/DSE-Aug20-SLC-BLR-Feb8-11/US_Heart_Patients.csv")
df=df.sample(frac=1,random_state=4).reset_index(drop=True)
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     0   67        1.0              1         3.0     0.0                0   
1     1   51        4.0              0         0.0     0.0                0   
2     0   48        3.0              1         9.0     0.0                0   
3     0   44        3.0              1        20.0     0.0                0   
4     0   64        2.0              0         0.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             1         0    270.0  137.5   72.5  35.01       85.0     73.0   
1             0         0    260.0  127.5   92.0  32.98       56.0     93.0   
2             1         0    266.0  155.0  100.0  27.86       75.0     84.0   
3             1         0    284.0  143.0   92.0  21.19       84.0     88.0   
4             1         0    279.0  172.0   87.0  24.01       80.0     70.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           0  
4           0

In [3]:
df.dtypes

male                 int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
TenYearCHD           int64
dtype: object

In [3]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [4]:
df=df.fillna(method='ffill')

In [5]:
y=df['TenYearCHD']
x=df.drop('TenYearCHD',axis=1)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [7]:
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,roc_curve
lc=LogisticRegression(solver='liblinear')
lc.fit(x_train,y_train)

y_train_pred=lc.predict(x_train)
y_train_prob=lc.predict_proba(x_train)[:,1]
print('train - confusion matrix : ','\n',confusion_matrix(y_train,y_train_pred))
print('train - accuracy score : ','\n', accuracy_score(y_train,y_train_pred))
print('train - AUC : ', roc_auc_score(y_train,y_train_prob))
print()
y_test_pred=lc.predict(x_test)
y_test_prob=lc.predict_proba(x_test)[:,1]
print('test - confusion matrix : ','\n',confusion_matrix(y_test,y_test_pred))
print('test - accuracy score : ','\n', accuracy_score(y_test,y_test_pred))
print('test - AUC : ', roc_auc_score(y_test,y_test_prob))

train - confusion matrix :  
 [[2523    7]
 [ 415   23]]
train - accuracy score :  
 0.8578167115902965
train - AUC :  0.72170574115184

test - confusion matrix :  
 [[1062    4]
 [ 196   10]]
test - accuracy score :  
 0.8427672955974843
test - AUC :  0.7315206105757847


In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,roc_curve
lc=LogisticRegression(solver='liblinear')
def model_eval(algo,xtrain,ytrain,xtest,ytest):
    algo.fit(xtrain,ytrain)

    y_train_pred=algo.predict(xtrain)
    y_train_prob=algo.predict_proba(xtrain)[:,1]
    print('train - confusion matrix : ','\n',confusion_matrix(ytrain,y_train_pred))
    print('train - accuracy score : ','\n', accuracy_score(ytrain,y_train_pred))
    print('train - AUC : ', roc_auc_score(ytrain,y_train_prob))
    print()
    print()
    y_test_pred=algo.predict(xtest)
    y_test_prob=algo.predict_proba(xtest)[:,1]
    print('test - confusion matrix : ','\n',confusion_matrix(ytest,y_test_pred))
    print('test - accuracy score : ','\n', accuracy_score(ytest,y_test_pred))
    print('test - AUC : ', roc_auc_score(ytest,y_test_prob))

In [9]:
model_eval(lc,x_train,y_train,x_test,y_test)

train - confusion matrix :  
 [[2523    7]
 [ 415   23]]
train - accuracy score :  
 0.8578167115902965
train - AUC :  0.72170574115184


test - confusion matrix :  
 [[1062    4]
 [ 196   10]]
test - accuracy score :  
 0.8427672955974843
test - AUC :  0.7315206105757847


# undersample Majority class

In [10]:
xy_train = pd.concat([x_train,y_train],axis=1)
print("Before Sampling:\n",xy_train["TenYearCHD"].value_counts())

xy_train0 = xy_train[xy_train["TenYearCHD"]==0]
xy_train1 = xy_train[xy_train["TenYearCHD"]==1]

len0 = len(xy_train0)
len1 = len(xy_train1)

xy_train0_us = xy_train0.sample(len1,random_state=4)
xy_train_us = pd.concat([xy_train0_us,xy_train1],axis=0)
print("After Sampling:\n",xy_train_us["TenYearCHD"].value_counts())

y_train_us = xy_train_us["TenYearCHD"]
x_train_us = xy_train_us.drop("TenYearCHD",axis=1)

Before Sampling:
 0    2530
1     438
Name: TenYearCHD, dtype: int64
After Sampling:
 1    438
0    438
Name: TenYearCHD, dtype: int64


In [11]:
model_eval(lc,x_train_us,y_train_us,x_test,y_test)

train - confusion matrix :  
 [[285 153]
 [152 286]]
train - accuracy score :  
 0.6518264840182648
train - AUC :  0.7155501344842685


test - confusion matrix :  
 [[737 329]
 [ 73 133]]
test - accuracy score :  
 0.6839622641509434
test - AUC :  0.7373631577988671


# oversample majority class

In [12]:
xy_train = pd.concat([x_train,y_train],axis=1)
print("Before Sampling:\n",xy_train["TenYearCHD"].value_counts())

xy_train0 = xy_train[xy_train["TenYearCHD"]==0]
xy_train1 = xy_train[xy_train["TenYearCHD"]==1]

len0 = len(xy_train0)
len1 = len(xy_train1)

xy_train1_os = xy_train1.sample(len0,replace=True,random_state=4)
xy_train_os = pd.concat([xy_train1_os,xy_train0],axis=0)
print("After Sampling:\n",xy_train_os["TenYearCHD"].value_counts())

y_train_os = xy_train_os["TenYearCHD"]
x_train_os = xy_train_os.drop("TenYearCHD",axis=1)

Before Sampling:
 0    2530
1     438
Name: TenYearCHD, dtype: int64
After Sampling:
 1    2530
0    2530
Name: TenYearCHD, dtype: int64


In [13]:
model_eval(lc,x_train_os,y_train_os,x_test,y_test)

train - confusion matrix :  
 [[1705  825]
 [ 792 1738]]
train - accuracy score :  
 0.6804347826086956
train - AUC :  0.7327399271977377


test - confusion matrix :  
 [[741 325]
 [ 72 134]]
test - accuracy score :  
 0.6878930817610063
test - AUC :  0.7399132953241407


## smote for oversampling minority class

In [14]:
# !pip install imblearn

In [15]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [16]:
from imblearn.over_sampling import SMOTE

In [17]:
smote=SMOTE(sampling_strategy='minority',random_state=4)
x_train_sm,y_train_sm=smote.fit_sample(x_train,y_train)

In [18]:
model_eval(lc,x_train_sm,y_train_sm,x_test,y_test)

train - confusion matrix :  
 [[1726  804]
 [ 818 1712]]
train - accuracy score :  
 0.6794466403162055
train - AUC :  0.7461239825649518


test - confusion matrix :  
 [[732 334]
 [ 95 111]]
test - accuracy score :  
 0.6627358490566038
test - AUC :  0.6570975791908777
